name: Run tests in simulation

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TURTLEBOT3_MODEL: burger

jobs:
  simulation:
    container: public.ecr.aws/docker/library/ros:melodic-robot
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: catkin_ws/
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
            ros-melodic-turtlebot3 \
            ros-melodic-turtlebot3-simulations \
            ros-melodic-gazebo*

      - name: Build workspace
        run: |
          source /opt/ros/melodic/setup.bash
          catkin_make

      - name: Run tests
        run: |
          source devel/setup.bash &&
          rostest my_turtlebot_sim my_turtlebot_sim.test --text
